fx_version 'cerulean'
game 'gta5'

author 'InterSystems'
description 'Speed Camera System'
version '1.1.1'
lua54 'yes'

shared_script '@es_extended/imports.lua' -- Qb-core - do we need comment out this line?

dependencies {
    'oxmysql',
    'PolyZone'
}

ui_page 'html/index.html'

files {
    'html/index.html',
    'html/style.css',
    'html/script.js',
    'html/jquery.min.js',
    'html/antiradar.png',
    'html/police_antiradar_detector.png',
    'shared/locales/notifications_*.lua'
}

shared_scripts {
    'shared/config.lua',
    'bridge/framework_bridge_shared.lua',
    'shared/locales/locales_finder/locales.lua'
}

server_scripts {
    '@oxmysql/lib/MySQL.lua',
    'bridge/framework_bridge_server.lua',
    'bridge/edit_notifications/server_notifications.lua',
    'server/server.lua',
    'server/mobile_speed_cam_server.lua',
    'server/wanted_racer_server.lua',
    'server/police_antiradar_scanner_server.lua',
    'server/server_webhooks_config/config_webhooks.lua',
    'server/server_webhooks_config/server_webhooks.lua',
    'server/version/version_check.lua',
    'server/billings/esx_billing.lua',
    'server/customise_targets/target_handler_server.lua'
}

client_scripts {
    '@PolyZone/client.lua',
    '@PolyZone/BoxZone.lua',
    '@PolyZone/CircleZone.lua',
    'bridge/framework_bridge_client.lua',
    'bridge/edit_notifications/client_notifications.lua',
    'client/client.lua',
    'client/mobile_speed_cam_client.lua',
    'client/wanted_racer_client.lua',
    'client/police_antiradar_scanner_client.lua',
    'client/customise_targets/ox_target_client.lua',
    'client/customise_targets/qb_target_client.lua'
}

-- This is for current & future addons
client_export 'GetActiveMobileRadars'
client_export 'GetFrameworkObject'
client_export 'GetConfig'
client_export 'TriggerNotification'
server_export 'GetNotifications'
server_export 'GetPlayerRadarCount'

escrow_ignore {
    'shared/config.lua',
    'shared/notifications.lua',
    'server/server_webhooks_config/config_webhooks.lua',
    'bridge/edit_notifications/client_notifications.lua',
    'bridge/edit_notifications/server_notifications.lua',
    'bridge/framework_bridge_shared.lua',
    'bridge/framework_bridge_server.lua',
    'bridge/framework_bridge_client.lua',
    'autogenerated_objects.lua',
    'autogenerated_radars.lua',
    'autogenerated_zones.lua',
    'shared/locales/*',
    'client/customise_targets/*',
    'server/customise_targets/*',
}
dependency '/assetpacks'